version: '3'

services:
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_HOST: '%'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
