# Generated by Django 3.2.6 on 2022-07-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_office', models.CharField(max_length=100, verbose_name='Филиал')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('hire_day', models.DateField(verbose_name='Дата приема на работу')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
            ],
        ),
    ]
